/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as ZipsRouteImport } from './routes/zips'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as CreateDoneRouteImport } from './routes/create.done'
import { Route as CreateProgressRouteImport } from './routes/create.progress'
import { Route as CreateSettingsRouteImport } from './routes/create.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ZipsRoute = ZipsRouteImport.update({
  id: '/zips',
  path: '/zips',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateDoneRoute = CreateDoneRouteImport.update({
  id: '/create/done',
  path: '/create/done',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateProgressRoute = CreateProgressRouteImport.update({
  id: '/create/progress',
  path: '/create/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateSettingsRoute = CreateSettingsRouteImport.update({
  id: '/create/settings',
  path: '/create/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/transfer': typeof TransferRoute
  '/zips': typeof ZipsRoute
  '/create/done': typeof CreateDoneRoute
  '/create/progress': typeof CreateProgressRoute
  '/create/settings': typeof CreateSettingsRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/transfer': typeof TransferRoute
  '/zips': typeof ZipsRoute
  '/create/done': typeof CreateDoneRoute
  '/create/progress': typeof CreateProgressRoute
  '/create/settings': typeof CreateSettingsRoute
  '/create': typeof CreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/transfer': typeof TransferRoute
  '/zips': typeof ZipsRoute
  '/create/done': typeof CreateDoneRoute
  '/create/progress': typeof CreateProgressRoute
  '/create/settings': typeof CreateSettingsRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/transfer'
    | '/zips'
    | '/create/done'
    | '/create/progress'
    | '/create/settings'
    | '/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/transfer'
    | '/zips'
    | '/create/done'
    | '/create/progress'
    | '/create/settings'
    | '/create'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/transfer'
    | '/zips'
    | '/create/done'
    | '/create/progress'
    | '/create/settings'
    | '/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  TransferRoute: typeof TransferRoute
  ZipsRoute: typeof ZipsRoute
  CreateDoneRoute: typeof CreateDoneRoute
  CreateProgressRoute: typeof CreateProgressRoute
  CreateSettingsRoute: typeof CreateSettingsRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zips': {
      id: '/zips'
      path: '/zips'
      fullPath: '/zips'
      preLoaderRoute: typeof ZipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/done': {
      id: '/create/done'
      path: '/create/done'
      fullPath: '/create/done'
      preLoaderRoute: typeof CreateDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/progress': {
      id: '/create/progress'
      path: '/create/progress'
      fullPath: '/create/progress'
      preLoaderRoute: typeof CreateProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/settings': {
      id: '/create/settings'
      path: '/create/settings'
      fullPath: '/create/settings'
      preLoaderRoute: typeof CreateSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  TransferRoute: TransferRoute,
  ZipsRoute: ZipsRoute,
  CreateDoneRoute: CreateDoneRoute,
  CreateProgressRoute: CreateProgressRoute,
  CreateSettingsRoute: CreateSettingsRoute,
  CreateIndexRoute: CreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
